classname: pipelines.assist.pipeline.Assist

triggers:
  - .*sb\.assist\.z01\.00.*\.assistsummary.cdf

retriever:
  path: pipelines/assist/config/retriever.yaml

dataset:
  path: pipelines/assist/config/dataset.yaml
  overrides:
    /attrs/location_id: sb
    /attrs/location_meaning: "Site B"
    /data_vars/longitude/data: -97.558676
    /data_vars/latitude/data: 36.231763

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
