classname: pipelines.wind_cube_profile_rtd.pipeline.WindCubeProfile

triggers:
  - .*WLS.*\.rtd.7z
  - .*sb.lidar.z01.*\.rtd.7z

retriever:
  path: pipelines/wind_cube_profile_rtd/config/retriever.yaml

dataset:
  path: pipelines/wind_cube_profile_rtd/config/dataset.yaml
  overrides:
    /attrs/location_id: sb
    /attrs/location_meaning: "Site B"
    /data_vars/longitude/data: -97.558676
    /data_vars/latitude/data: 36.231763

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
