pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "nwtc"
  dataset_name: "wind_cube_nacelle_sta"
  # qualifier: ""
  # temporal: ""
  data_level: "b0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "wind_cube_nacelle"
    description: "Wind cube v2 ingest"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "nwtc"

  dimensions:
    time:
      length: unlimited

  variables:
    time:
      input:
        name: Date_and_Time
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y-%m-%dT%H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    CNR0:
      attrs:
        long_name: Carrier-to-noise ratio along LOS0 (average data).
        units: dB
      dims: [time]
      input:
        name: CNR0
      type: float
    CNR1:
      attrs:
        long_name: Carrier-to-noise ratio along LOS1 (average data).
        units: dB
      dims: [time]
      input:
        name: CNR1
      type: float
    CNR2:
      attrs:
        long_name: Carrier-to-noise ratio along LOS2 (average data).
        units: dB
      dims: [time]
      input:
        name: CNR2
      type: float
    CNR3:
      attrs:
        long_name: Carrier-to-noise ratio along LOS3 (average data).
        units: dB
      dims: [time]
      input:
        name: CNR3
      type: float
    DIRECTION_high:
      attrs:
        long_name: Horizontal wind direction above hub (average data).
        units: deg
      dims: [time]
      input:
        name: DIRECTION_high
      type: float
    DIRECTION_hub:
      attrs:
        long_name: Horizontal wind direction at hub height.
        units: deg
      dims: [time]
      input:
        name: DIRECTION_hub
      type: float
    DIRECTION_low:
      attrs:
        long_name: Horizontal wind direction below hub (average data).
        units: deg
      dims: [time]
      input:
        name: DIRECTION_low
      type: float
    Distance:
      attrs:
        long_name: Measurement plan distance.
        units: m
      dims: [time]
      input:
        name: Distance
      type: float
    HEIGHT_high:
      attrs:
        long_name: Measurement height of the beams from the top (average data).
        units: m
      dims: [time]
      input:
        name: HEIGHT_high
      type: float
    HEIGHT_low:
      attrs:
        long_name: Measurement height of the bottom beams (average data).
        units: m
      dims: [time]
      input:
        name: HEIGHT_low
      type: float
    HWS_high:
      attrs:
        long_name: Horizontal wind speed above hub (average data).
        units: m/s
      dims: [time]
      input:
        name: HWS_high
      type: float
    HWS_high_Availability:
      attrs:
        long_name: Availability of the reconstruction above hub (average data).
        units: "%"
      dims: [time]
      input:
        name: HWS_high_Availability
      type: float
    HWS_hub:
      attrs:
        long_name: Horizontal wind speed at hub height.
        units: m/s
      dims: [time]
      input:
        name: HWS_hub
      type: float
    HWS_hub_availability:
      attrs:
        long_name: Availability of the reconstruction at hub height.
        units: "%"
      dims: [time]
      input:
        name: HWS_hub_availability
      type: float
    HWS_low:
      attrs:
        long_name: Horizontal wind speed below hub (average data).
        units: m/s
      dims: [time]
      input:
        name: HWS_low
      type: float
    HWS_low_Availability:
      attrs:
        long_name: Availability of the reconstruction below hub (average data).
        units: "%"
      dims: [time]
      input:
        name: HWS_low_Availability
      type: float
    RWS0:
      attrs:
        long_name: Radial wind speed along LOS0 (average data).
        units: m/s
      dims: [time]
      input:
        name: RWS0
      type: float
    RWS0_availability:
      attrs:
        long_name: Availability of the radial measurement along LOS0.
        units: "%"
      dims: [time]
      input:
        name: RWS0_availability
      type: float
    RWS1:
      attrs:
        long_name: Radial wind speed along LOS1 (average data).
        units: m/s
      dims: [time]
      input:
        name: RWS1
      type: float
    RWS1_availability:
      attrs:
        long_name: Availability of the radial measurement along LOS1.
        units: "%"
      dims: [time]
      input:
        name: RWS1_availability
      type: float
    RWS2:
      attrs:
        long_name: Radial wind speed along LOS2 (average data).
        units: m/s
      dims: [time]
      input:
        name: RWS2
      type: float
    RWS2_availability:
      attrs:
        long_name: Availability of the radial measurement along LOS2.
        units: "%"
      dims: [time]
      input:
        name: RWS2_availability
      type: float
    RWS3:
      attrs:
        long_name: Radial wind speed along LOS3 (average data).
        units: m/s
      dims: [time]
      input:
        name: RWS3
      type: float
    RWS3_availability:
      attrs:
        long_name: Availability of the radial measurement along LOS3.
        units: "%"
      dims: [time]
      input:
        name: RWS3_availability
      type: float
    Roll:
      attrs:
        long_name: Roll angle of the telescope (average data).
        units: deg
      dims: [time]
      input:
        name: Roll
      type: float
    Shear:
      attrs:
        long_name: Vertical wind shear coefficient.
        units: NA
      dims: [time]
      input:
        name: Shear
      type: float
    TI0:
      attrs:
        long_name: Turbulence intensity along LOS0 (average data).
        units: NA
      dims: [time]
      input:
        name: TI0
      type: float
    TI1:
      attrs:
        long_name: Turbulence intensity along LOS1 (average data).
        units: NA
      dims: [time]
      input:
        name: TI1
      type: float
    TI2:
      attrs:
        long_name: Turbulence intensity along LOS2 (average data).
        units: NA
      dims: [time]
      input:
        name: TI2
      type: float
    TI3:
      attrs:
        long_name: Turbulence intensity along LOS3 (average data).
        units: NA
      dims: [time]
      input:
        name: TI3
      type: float
    TI_gain:
      attrs:
        long_name: Turbulence intensity gain (average data).
        units: NA
      dims: [time]
      input:
        name: TI_gain
      type: float
    TI_high:
      attrs:
        long_name: Turbulence intensity above hub (average data).
        units: "%"
      dims: [time]
      input:
        name: TI_high
      type: float
    TI_hub:
      attrs:
        long_name: Turbulence intensity at hub height.
        units: NA
      dims: [time]
      input:
        name: TI_hub
      type: float
    TI_low:
      attrs:
        long_name: Turbulence intensity below hub (average data).
        units: "%"
      dims: [time]
      input:
        name: TI_low
      type: float
    Tilt:
      attrs:
        long_name: Tilt angle of the telescope (average data).
        units: deg
      dims: [time]
      input:
        name: Tilt
      type: float
    U_high:
      attrs:
        long_name: Longitudinal component of the wind above hub (average data).
        units: m/s
      dims: [time]
      input:
        name: U_high
      type: float
    U_low:
      attrs:
        long_name: Longitudinal component of the wind below hub (average data).
        units: m/s
      dims: [time]
      input:
        name: U_low
      type: float
    V_high:
      attrs:
        long_name: Transversal component of the wind above hub (average data).
        units: m/s
      dims: [time]
      input:
        name: V_high
      type: float
    V_low:
      attrs:
        long_name: Transversal component of the wind below hub (average data).
        units: m/s
      dims: [time]
      input:
        name: V_low
      type: float
    Veer:
      attrs:
        long_name: Vertical wind veer coefficient (average data).
        units: deg/m
      dims: [time]
      input:
        name: Veer
      type: float

    latitude:
      data: 71.323
      type: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        comment: "Recorded lattitude at the instrument location"
        units: "degree_N"
        valid_range: [-90.f, 90.f]

    longitude:
      data: -156.609
      type: float
      attrs:
        long_name: "East longitude"
        standard_name: "longitude"
        comment: "Recorded longitude at the instrument location"
        units: "degree_E"
        valid_range: [-180.f, 180.f]

    altitude:
      data: 4000.0
      type: float
      attrs:
        long_name: "altitude"
        standard_name: "altitude"
        comment: "Recorded altitude at the instrument location"
        units: m

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - COORDS

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: [latitude, longitude, altitude]

  # manage_custom_qc: # Rename this
  #   checker:
  #     classname: ingest.wind_cube_profile.pipeline.qc.CustomQualityChecker
  #   handlers:
  #     - classname: ingest.wind_cube_profile.pipeline.qc.CustomQualityHandler
